PetaStarter/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
namespace DeMonte.Controllers
{
    [Authorize(Roles = "Boss,hr")]
    public class RegisterController : EAController
    {
        // GET: Clients
        public ActionResult Index(int? page, string PropName)
        {
            if (PropName?.Length > 0) page = 1;
            return View("Index", base.BaseIndex<RegisterViewCls>(page, "Register where CustomerID like '%" + PropName + "%'"));
        }

        public ActionResult Filter()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ViewRegister(DateTime FromDt, DateTime ToDt)
        {
            db.Execute("exec GetRegister @0, @1", FromDt, ToDt);
            var vwData = db.Fetch<RegisterViewCls>("Select * from RptRegister order by RegisterNo");
            
            return View(vwData);
        }

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PetaStarter/Views/Register/Details.cshtml
@model DeMonte.RptRegister
@{
    ViewBag.Title = "Details";
    Layout = "";
}
<div class="section-to-print" style="background-image: url('/Custom/BkGrnd.png'); background-repeat: no-repeat; background-attachment: fixed; background-position: center; ">
    @Html.Partial("_LetterHead")

    <table border="1px">
        <tr>
           
            <th>Name of Guest</th>
            <th>Full Address India/Abroad</th>
            <th>Passport No date of Issue and expiry</th>
            <th>No. Guest</th>
            <th>No. Rooms</th>
            <th>Date of Arrival and time</th>
            <th>Date of Departure and time</th>
            <th>Accomodations charges per day</th>
            <th>Room No</th>
            <th>Sign of Guest during arrival</th>
            <th>Period to stay(Total days)</th>
            <th>Total amount charges on accomodation</th>
            <th>Charges paid in Foreign/Indian Currency</th>
            <th>Bill/Receipt No</th>
            <th>Sign. of receptionist or manager on duty</th>
            <th>GST</th>
            <th>Particulars of encashment with date</th>
            <th>Sign of Guest during departure</th>
            <th>Remarks</th>
        </tr>

        <tr>
        
        <td>@Html.DisplayFor(model => model.Name)</td>
        <td>@Html.DisplayFor(model => model.Address)</td>
        <td>@Html.DisplayFor(model => model.PassportDet)</td>
        <td>@Html.DisplayFor(model => model.NoOfGuest)</td>
        <td>@Html.DisplayFor(model => model.NoOfRooms)</td>
        <td>@Html.DisplayFor(model => model.DateArrivalTime)</td>
        <td>@Html.DisplayFor(model => model.DateDepartureTime)</td>
        <td>@Html.DisplayFor(model => model.ChargesPerDay)</td>
        <td>@Html.DisplayFor(model => model.RoomNo)</td>
        <td></td>                     
        <td>@Html.DisplayFor(model => model.TotalDays)</td>
        <td>@Html.DisplayFor(model => model.TotalCharges)</td>
        <td>@Html.DisplayFor(model => model.PaidInForeignIndian)</td>
        <td>@Html.DisplayFor(model => model.BillReceiptNo)</td>
        <td></td>                     
        <td>@Html.DisplayFor(model => model.GST)</td>
        <td>@Html.DisplayFor(model => model.EncashCertDetails)</td>
        <td></td>                     
        <td>@Html.DisplayFor(model => model.Remarks)</td>
        </tr>
        
        
    </table>

</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
    &nbsp;

<p class="section-to-not-print">
    <input type="button" onclick="javascript:window.print();" value="Print" class="eabutton section-to-not-print" />
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PetaStarter/Views/Register/Filter.cshtml
@{
    ViewBag.Title = "Filter register";
}

<h2>Please choose the dates for which you want to see the Register</h2>


@using (Html.BeginForm("ViewRegister", "Register", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" >
            @Html.Label("View Register From:" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="FromDt" name="FromDt" type="date" value="@(String.Format("{0:yyyy-MM-dd}",DateTime.Today.AddMonths(-1).Date))" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("View Register To:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="ToDt" name="ToDt"  type="date" value="@(String.Format("{0:yyyy-MM-dd}",DateTime.Today.Date))" class="form-control" />
            </div>
        </div>

      
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Fetch" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PetaStarter/Views/Register/Index.cshtml
@model PagedList.IPagedList<RptRegister>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Register";
}

<center>
    <h2 class="section-to-print"><b>Search for Customer records</b></h2>
    
    @using (Html.BeginForm("Index", "Register", FormMethod.Post))
    {
        @Html.AntiForgeryToken()


        <div class="form-group">
            @Html.Label("From Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="fromdate" type="date" class="form-control text-box single-line valid" id="fromdate" aria-invalid="false" aria-describedby="Date-error" type="text" data-val-number="The field Others 1 must be a number." data-val="true" data-val-range-min="0" data-val-range-max="1.79769313486232E+308" data-val-range="The field Others 1 must be between 0 and 1.79769313486232E+308.">
             
            </div>
        </div>
        <br></br>
        <div class="form-group">
            @Html.Label("To Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="todate" type="date" class="form-control text-box single-line valid" id="todate" aria-invalid="false" aria-describedby="Date-error" type="text" data-val-number="The field Others 1 must be a number." data-val="true" data-val-range-min="0" data-val-range-max="1.79769313486232E+308" data-val-range="The field Others 1 must be between 0 and 1.79769313486232E+308.">

            </div>
        </div>
        <br></br>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    }
</center>

PetaStarter/Views/Register/RegisterScreen.cshtml
@model IEnumerable<DeMonte.RptRegister>

@{
    ViewBag.Title = "Register";
}

<h2> TOURIST REGISTER</h2>
<style>
    #arrange th{
        text-align:center;
    }
</style>
<div class="section-to-print" style="background-image: url('/Custom/BkGrnd.png'); background-repeat: no-repeat; background-attachment: fixed; background-position: center; ">
    @Html.Partial("_LetterHead")
    </br>
    <table id ="arrange" border="1px">
        <tr>
            <th>Sr No</th>
            <th>Name of Guest</th>
            <th>Full Address India/Abroad</th>
            <th>Passport No date of Issue and expiry</th>
            <th>No. Guest</th>
            <th>No. Rooms</th>
            <th>Date of Arrival and time</th>
            <th>Date of Departure and time</th>
            <th >Accomodations charges per day</th>
            <th >Room No</th>
            <th>Sign of Guest during arrival</th>
            <th >Period to stay(Total days)</th>
            <th >Total amount charges on accomodation</th>
            <th >Charges paid in Foreign/Indian Currency</th>
            <th >Bill/Receipt No</th>
            <th>Sign. of receptionist or manager on duty</th>
            <th>GST</th>
            <th>Particulars of encashment with date</th>
            <th>Sign of Guest during departure</th>
            <th>Remarks</th>
            <th></th>
        </tr>
        
                      @{int i = 1;   }
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@i</td>
                            <td>@Html.DisplayFor(modelItem => item.Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.Address)</td>
                            <td>@Html.DisplayFor(modelItem => item.PassportDet)</td>
                            <td>@Html.DisplayFor(modelItem => item.NoOfGuest)</td>
                            <td>@Html.DisplayFor(modelItem => item.NoOfRooms)</td>
                            <td>@Html.DisplayFor(modelItem => item.DateArrivalTime)</td>
                            <td>@Html.DisplayFor(modelItem => item.DateDepartureTime)</td>
                            <td>@Html.DisplayFor(modelItem => item.ChargesPerDay)</td>
                            <td>@Html.DisplayFor(modelItem => item.RoomNo)</td>
                            <td></td>
                            <td>@Html.DisplayFor(modelItem => item.TotalDays)</td>
                            <td>@Html.DisplayFor(modelItem => item.TotalCharges)</td>
                            <td>@Html.DisplayFor(modelItem => item.PaidInForeignIndian)</td>
                            <td>@Html.DisplayFor(modelItem => item.BillReceiptNo)</td>
                            <td></td>
                            <td>@Html.DisplayFor(modelItem => item.GST)</td>
                            <td>@Html.DisplayFor(modelItem => item.EncashCertDetails)</td>
                            <td></td>
                            <td>@Html.DisplayFor(modelItem => item.Remarks)</td>
                            <td> @Html.ActionLink("Details", "Details", new { BID = item.BillID })</td>
                        </tr>
                        i++;
                    }
    </table>
</div>
</br>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

PetaStarter/Views/Register/ViewRegister.cshtml
@model IEnumerable<DeMonte.RegisterViewCls>

@{
    ViewBag.Title = "Register";
    Layout = "";
}

<style>
    table {
        border-collapse: collapse;
    }

    #grid table, #grid th, #grid td {
        border: 1px solid;
        text-align: right;
    }
</style>
<div class="section-to-print" style="background-image: url('/Custom/BkGrnd.png'); background-repeat: no-repeat; background-attachment: fixed; background-position: center; ">
    <table width="100%">
        <tr>
            <td style="text-align:left;">
                <h3>Form XI (See Rule 10)</h3>
                <h1>TOURIST REGISTER</h1>
            </td>
            <td>
                @Html.Partial("_LetterHead")
            </td>
            <td style="text-align:right;">
                Form 2 [See Rule 3(I) (b)] of<br />
                The Goa Tax on Luxuries (Hotel & Lodging Houses) Rules 1988<br />
                Daily account of occupancy of rooms & collection of tax
            </td>
        </tr>
    </table>
    <br />
    <table width="100%" id="grid">
     <tr>
         <td style="text-align:center;" width="1.5%">Sr. No.</td>
         <td style="text-align:center;" width="12%">Name of Guest</td>
         <td style="text-align:center;" width="10.5%">Full address in India/abroad</td>
         <td style="text-align:center;" width="5%">Passport No. date of issue and expiry</td>
         <td style="text-align:center;" colspan="2" width="5%">No. of guests acc. and No. of rooms occupied</td>
         <td style="text-align:center;" width="5%">Date of arrival and time</td>
         <td style="text-align:center;" width="5%">Date of departure and time</td>
         <td style="text-align:center;" width="5%">Accommodation charges per day</td>
         <td style="text-align:center;" colspan="2" width="5%">Room No/Period of stay</td>
         <td style="text-align:center;" width="5%">Sign of Guest during arrival</td>
         <td style="text-align:center;" width="5%">Total amount charges on accommodation</td>
         <td style="text-align:center;" width="5%">Charges paid in foreign/Indian currency</td>
         <td style="text-align:center;" width="5%">Bill/receipt no. and cash memo with date</td>
         <td style="text-align:center;" width="5%">Amount of GST collected</td>
         <td style="text-align:center;" width="5%">Sign of Receptionist or Manager on duty</td>
         <td style="text-align:center;" width="5%">Particulars of encashment certificate with date</td>
         <td style="text-align:center;" width="5%">Sign of Guest during departure</td>
         <td style="text-align:center;" width="6%">Remarks</td>
     </tr>   
        <tr>
            <td style="text-align:center;">1</td>
            <td style="text-align:center;">2</td>
            <td style="text-align:center;">3</td>
            <td style="text-align:center;">4</td>
            <td style="text-align:center;" colspan="2">5</td>
            <td style="text-align:center;">6</td>
            <td style="text-align:center;">7</td>
            <td style="text-align:center;">8</td>
            <td style="text-align:center;" colspan="2">9</td>
            <td style="text-align:center;">10</td>
            <td style="text-align:center;">11</td>
            <td style="text-align:center;">12</td>
            <td style="text-align:center;">13</td>
            <td style="text-align:center;">14</td>
            <td style="text-align:center;">15</td>
            <td style="text-align:center;">16</td>
            <td style="text-align:center;">17</td>
            <td style="text-align:center;">18</td>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align:center;">@item.RegisterNo</td>
                <td style="text-align:left;">@item.Name</td>
                <td style="text-align:left;">@item.Address</td>
                <td style="text-align:left;">@item.PassportDet</td>
                <td style="text-align:center;">@item.NoOfGuest</td>
                <td style="text-align:center;">@item.NoOfRooms</td>
                <td style="text-align:left;">@(String.Format("{0:dd-MM-yy HH:mm}", item.DateArrivalTime))</td>
                <td style="text-align:left;">@(String.Format("{0:dd-MM-yy HH:mm}", item.DateDepartureTime))</td>
                <td style="text-align:right;">@item.ChargesPerDay</td>
                <td style="text-align:center;">@item.RoomNo</td>
                <td style="text-align:center;">@item.TotalDays</td>
                <td style="text-align:left;"></td>
                <td style="text-align:right;">@item.TotalCharges</td>
                <td style="text-align:right;">@item.PaidInForeignIndian</td>
                <td style="text-align:center;">@item.BillReceiptNo</td>
                <td style="text-align:right;">@item.GST</td>
                <td style="text-align:left;"></td>
                <td style="text-align:left;">@item.EncashCertDetails</td>
                <td style="text-align:left;"></td>
                <td style="text-align:left;">@item.Remarks</td>
            </tr>
        }
        </table>
</div>


<p>

    @Html.ActionLink("Back to List", "Index")
    <input type="button" onclick="javascript:window.print();" value="Print" class="eabutton section-to-not-print" />
</p>