PetaStarter/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace DeMonte.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

PetaStarter/Controllers/BillNonResdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeMonte.Controllers
{
    [Authorize(Roles ="Boss,hr")]
    public class BillNonResdController : EAController
    {                
        public ActionResult Index(int? page, string PropName)
        {
            if (PropName?.Length > 0) page = 1;            
            return View("Index", base.BaseIndex<BillIndex>(page, "b.NonResdCust, b.BDate, b.BillID, b.BillNo, Canceled", "Bill b where CustomerId is NULL order by BillID desc"));
        }
        

        // GET: Clients/Create
        public ActionResult Manage(int? id)
        {
            var vwdata = base.BaseCreateEdit<Bill>(id, "BillID");
            
            return View(vwdata);
        }
        
        // POST: Customer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Manage([Bind(Include = "BillID,BillNo,BDate,BillReceiptNo,PaidInForeignIndian,CGST,SGST,IGST,EncashCertDetails,Remarks,GSTExport, NonResdCust,NRCgst")] Bill bill)
        {
            using (var transaction = db.GetTransaction())
            {
                try
                {
                    //Save the Bill record
                    int b;
                    bill.TotalDays = 0;
                    if (bill.BillID > 0)
                    {
                        db.Update(bill);
                        b = bill.BillID;
                    }
                    else
                    {                        
                        b = (int)db.Insert(bill);                
                    }

                    //Insert Placeholder BillDetail records, but first delete the orphans (if any)            
                    var vwdata = db.Query<BillDetail>("where BillID=@0", b);
                    var killbill = vwdata.ToArray();
                    foreach (var item in killbill)
                    {
                        db.Delete<BillDetail>(item.BillDetailID);
                    }
                                
                    db.Insert(new BillDetail { BillID = b, Date = bill.BDate, GST = 0 });
                            

                    transaction.Complete();
                    return RedirectToAction("Details", new { id = b });
                }
                catch (Exception ex)
                {
                    db.AbortTransaction();
                    throw ex;
                }
            }

        }

        

        /// <summary>
        /// Create BillDetail records
        /// </summary>
        /// <param name="id">Bill ID</param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            var viewdata = new BillScreen();
            viewdata.Bill = db.FirstOrDefault<Bill>("where BillID=@0", id);            
            viewdata.BillDetails = db.Fetch<BillDetail>("where BillID =@0  order by [Date]", viewdata.Bill.BillID);
            
            return View("BillandDetails", viewdata);
        }

        public ActionResult ManageDetails (int? id)
        {
            var viewdata = new BillScreen();
            viewdata.FrmEdt = BaseCreateEdit<BillDetail>(id, "BillDetailID");
            viewdata.Bill = db.FirstOrDefault<Bill>("where BillID=@0", viewdata.FrmEdt.BillID);            
            viewdata.BillDetails = db.Fetch<BillDetail>("where BillID =@0", viewdata.Bill.BillID);

            return View("BillandDetails", viewdata);
        }

        // POST: Customer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ManageDetails([Bind(Include = "BillDetailID,BillID,Date,Miscelleneous,Other1,Other2,Other3,Other4")] BillDetail billdetail)
        {            
            var Billrec = db.FirstOrDefault<Bill>("where BillID = @0", billdetail.BillID);
            var TaxableValue = (billdetail.Miscelleneous ?? 0) + (billdetail.Other1 ?? 0) + (billdetail.Other2 ?? 0) + (billdetail.Other3 ?? 0) + (billdetail.Other4 ?? 0);

            var igst = (TaxableValue * (Billrec.IGST ?? 0) / 100);
            var cgst = (TaxableValue * (Billrec.CGST ?? 0) / 100);
            var sgst = (TaxableValue * (Billrec.SGST ?? 0) / 100);
            billdetail.GST = igst + cgst + sgst;
            db.Update(billdetail);
            return RedirectToAction("Details", new { id = billdetail.BillID });
        }

        public ActionResult Print(int? id)
        {
            var viewdata = new BillScreen();
                        
            viewdata.Bill = db.FirstOrDefault<Bill>("where BillID=@0", id);            
            viewdata.BillDetails = db.Fetch<BillDetail>("where BillID =@0  order by [Date]", viewdata.Bill.BillID);
            ViewBag.AdvanceAmt = db.Single<decimal>("Select coalesce(sum(Amount),0) from Receipt where BillNo = @0", id);

            return View("Print", viewdata);
        }

        public ActionResult Cancel(int? id)
        {
            var viewdata = new BillScreen();

            viewdata.Bill = db.FirstOrDefault<Bill>("where BillID=@0", id);
            
            viewdata.BillDetails = db.Fetch<BillDetail>("where BillID =@0  order by [Date]", viewdata.Bill.BillID);
            ViewBag.Receipts = db.Query<Receipt>("Select * from Receipt where BillNo = @0", id);

            return View("Cancel", viewdata);
        }

        [HttpPost]
        public ActionResult Cancel(int KillBill)
        {
            var kb = db.FirstOrDefault<Bill>("where BillID = @0", KillBill);
            kb.Canceled = true;
            db.Update(kb);
            return RedirectToAction("Index", "BillNonResd");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PetaStarter/Controllers/ReceiptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeMonte.Controllers
{
    [Authorize(Roles = "Boss,hr")]
    public class ReceiptController : EAController
    {
        // GET: Clients
        public ActionResult Index(int? page, int BillID)
        {
            page = 1;
            ViewBag.BillNo = db.Single<Bill>(BillID).BillNo;

            //Fetch the Bill details
            var RmCosts = db.Single<decimal>("Select coalesce(ChargesPerDay * TotalDays,0) from Bill where BillID=@0", BillID);
            var detailCosts = db.Single<decimal>("Select sum(coalesce(ExtraPerson,0)+coalesce(GST,0)+coalesce(Miscelleneous,0)+coalesce(Other1,0)+coalesce(Other2,0)+coalesce(Other3,0)+coalesce(Other4,0)) from BillDetail where BillID=@0", BillID);
            ViewBag.BillTotal = RmCosts + detailCosts;
            return View("Index", base.BaseIndex<Receipt>(page, "Receipt where  BillNo =" + BillID  + " order by ReceiptID desc"));
        }



        // GET: Clients/Create
        public ActionResult Manage(int? id, int BillID)
        {
            ViewBag.ReceiptTypeID = new SelectList(db.Fetch<ReceiptType>("Select * from ReceiptTypes"), "ReceiptTypeID", "Type");
            var vwdata = base.BaseCreateEdit<Receipt>(id, "ReceiptID");
            ViewBag.BillNo = BillID;
            return View(vwdata);
        }

        // POST: Customer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Manage([Bind(Include = "ReceiptID,TDate,Name,Amount,ChequeNo,ChqDate,DrawnOn, BillNo,ReceiptTypeID")] Receipt receipt)
        {
            receipt.RoomNo = db.Single<string>("Select RoomNo from Bill Where BillID = @0", receipt.BillNo);

            var res = (receipt.ReceiptID>0) ? db.Update(receipt) : db.Insert(receipt);

            return RedirectToAction("Index",new { BillID = receipt.BillNo});
        }

        public ActionResult Details(int? id)
        {
            var viewdata = base.BaseCreateEdit<Receipt>(id, "ReceiptID");
            ChangeNumbersToWords cntw = new ChangeNumbersToWords();
            ViewBag.recptAmt = cntw.changeToWords(viewdata.Amount.ToString());
            ViewBag.ReceiptTypeName = db.FirstOrDefault<string>("Select top 1 Type from ReceiptTypes where ReceiptTypeId = @0", viewdata.ReceiptTypeID);
            return View(viewdata);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PetaStarter/Views/BillNonResd/BillandDetails.cshtml
@model DeMonte.BillScreen

@{
    ViewBag.Title = "Manage";
}

<h2>Manage Bill Details</h2>

<div class="MastDet cont">
    <dl class="dl-horizontal">
        <dt>Customer</dt>
        <dd>@Model.Bill.NonResdCust</dd>
                
        <dt>Bill Number</dt>
        <dd>@Model.Bill.BillNo</dd>

        <dt>Advance Recpt. No.</dt>
        <dd>@Model.Bill.BillReceiptNo</dd>
                
        <dt>Bill Date</dt>
        <dd>@String.Format("{0:yyyy-MM-dd}", Model.Bill.BDate)</dd>
    </dl>
</div>

@if (Model.FrmEdt != null)
{    
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("BillID", (int)Model.Bill.BillID)
        @Html.Hidden("BillDetailID", (int)Model.FrmEdt.BillDetailID)
        @Html.Hidden("Date", (DateTime)Model.FrmEdt.Date)

        <div class="form-horizontal">
            <h4>Bill Details</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            
            <div class="form-group">
                <h3 class="col-md-2">&nbsp;</h3>            
                <h2 class="col-md-10"><u>@Html.DisplayFor(model => model.FrmEdt.Date, new { htmlAttributes = new { @class = "form-label" } })</u></h2>
                   
                
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FrmEdt.Miscelleneous, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input value=@Model.FrmEdt.Miscelleneous name="Miscelleneous" class="form-control text-box single-line valid" id="Miscelleneous" aria-invalid="false" aria-describedby="Miscelleneous-error" type="text" data-val-number="The field Miscelleneous must be a number." data-val="true">
                    @Html.ValidationMessageFor(model => model.FrmEdt.Miscelleneous, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FrmEdt.Other1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input value=@Model.FrmEdt.Other1 name="Other1" class="form-control text-box single-line valid" id="Other1" aria-invalid="false" aria-describedby="Other1-error" type="text" data-val-number="The field Others 1 must be a number." data-val="true" data-val-range-min="0" data-val-range-max="1.79769313486232E+308" data-val-range="The field Others 1 must be between 0 and 1.79769313486232E+308.">
                    @Html.ValidationMessageFor(model => model.FrmEdt.Other1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FrmEdt.Other2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input value=@Model.FrmEdt.Other2  name="Other2" class="form-control text-box single-line valid" id="Other2" aria-invalid="false" aria-describedby="Other2-error" type="text" data-val-number="The field Others 2 must be a number." data-val="true" data-val-range-min="0" data-val-range-max="1.79769313486232E+308" data-val-range="The field Others 2 must be between 0 and 1.79769313486232E+308.">
                    @Html.ValidationMessageFor(model => model.FrmEdt.Other2, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FrmEdt.Other3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input value=@Model.FrmEdt.Other3 name="Other3" class="form-control text-box single-line valid" id="Other3" aria-invalid="false" aria-describedby="Other3-error" type="text" data-val-number="The field Others 3 must be a number." data-val="true" data-val-range-min="0" data-val-range-max="1.79769313486232E+308" data-val-range="The field Others 3 must be between 0 and 1.79769313486232E+308.">
                    @Html.ValidationMessageFor(model => model.FrmEdt.Other3, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FrmEdt.Other4, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input value=@Model.FrmEdt.Other4 name="Other4" class="form-control text-box single-line valid" id="Other4" aria-invalid="false" aria-describedby="Other4-error" type="text" data-val-number="The field Others 4 must be a number." data-val="true" data-val-range-min="0" data-val-range-max="1.79769313486232E+308" data-val-range="The field Others 4 must be between 0 and 1.79769313486232E+308.">
                    @Html.ValidationMessageFor(model => model.FrmEdt.Other4, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
}

<br />
<div>    
    <a href="" onclick="window.history.go(-1); return false;" >Back to List</a> |
    @Html.ActionLink("Print", "Print", new { id = Model.Bill.BillID}, new { target="_blank"})
    
</div>
<hr />
<h2>Bill Details</h2>
<table class="table">
    <tr>
        <th>Date</th>        
        <th>Miscelleneous</th>
        <th>Other 1</th>
        <th>Other 2</th>
        <th>Other 3</th>
        <th>Other 4</th>
        <th>GST</th>
        <th></th>
    </tr>

    @foreach (var item in Model.BillDetails)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>            
            <td>
                @Html.DisplayFor(modelItem => item.Miscelleneous)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Other1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Other2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Other3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Other4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GST)
            </td>
            <td>
                @Html.ActionLink("Manage","ManageDetails",new { id = item.BillDetailID})
            </td>
        </tr>
    }

</table>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PetaStarter/Views/BillNonResd/Cancel.cshtml
@model DeMonte.BillScreen

@{
    ViewBag.Title = "Print Bill";
}

<style>
    table {
        border-collapse:collapse;
    }
    #grid table, #grid th, #grid td {
        border: 1px solid;
        text-align:right;
    }

</style>


   
<div class="section-to-print">
    @Html.Partial("_LetterHead")
    <br />

    @using (Html.BeginForm("Cancel", "BillNonResd", FormMethod.Post))
    {
        <div class="MastDet">
            <div class="form-group">
                @Html.Label("Are you sure you want to cancel this Bill and its associated receipts?", htmlAttributes: new { @class = "control-label col-md-8" })
                <br />
                <div class="col-md-4">
                    @Html.Hidden("KillBill", (int)Model.Bill.BillID)
                    <input type="submit" value="Cancel" class="btn btn-default" />
                    <input type="button" onclick="window.history.go(-1); return false;" value="Dont Cancel" class="btn btn-default" />
                <br />
                </div>
            </div>
        </div>
    }

    <br />

    <table width="100%">
        <tr>
            <td width="30%">No.: <u>@Model.Bill.BillNo</u></td>
            <td style="text-align:right;" width="30%"><h2>INVOICE</h2></td>
            <td style="text-align:right;" width="40%">
                Date:   <u>@(String.Format("{0:dd-MMM-yy}",Model.Bill.BDate))</u>
            </td>
        </tr>
        <tr>
            <td colspan="3">Name: <u>@Model.Bill.NonResdCust</u></td>
        </tr>
        <tr>
            <td colspan="2">Guest GST: <u>@Model.Bill.NRCgst</u></td>
            <td>Room Charges per day: <u>@Model.Bill.ChargesPerDay</u></td>
        </tr>
    </table>
    <br />
    <table width="100%">
        <tr>
            <td width="16%">Date Of Arrival:</td>
            <td width="17%"><u>&nbsp;</u></td>
            <td width="16%">Departure Date:</td>
            <td width="17%"><u>&nbsp;</u></td>
            <td width="16%">Total Days:</td>
            <td width="17%"><u>&nbsp;</u></td>
        </tr>
        <tr>
            <td width="16%">Check in Time:</td>
            <td width="17%"><u>&nbsp;</u></td>
            <td width="16%">Check out Time:</td>
            <td width="17%"><u>&nbsp;</u></td>
            <td width="16%">No of Persons:</td>
            <td width="17%"><u>&nbsp;</u></td>
        </tr>
        <tr>
            <td width="16%">Register No:</td>
            <td width="17%"><u>@Model.Bill.RegisterNo</u></td>
            <td width="16%">Room No.:</td>
            <td width="17%"><u>&nbsp;</u></td>
            <td width="16%">Adv. Rcpt No.:</td>
            <td width="17%"><u>@Model.Bill.BillReceiptNo</u></td>
        </tr>
    </table>
    <br />
    <table id ="grid" width="100%">
        <tr>
            <td style="text-align:left;">Date</td>
            @foreach(var item in Model.BillDetails)
            {
                <td style="font-weight:bold;">@(String.Format("{0:yyyy-MM-dd}", item.Date))</td>
            }
        </tr>
        <tr>
            <td style="text-align:left;">Room Charges</td>
            @foreach (var item in Model.BillDetails)
            {
                <td>@Model.Bill.ChargesPerDay</td>
            }
        </tr>
        <tr>
            <td style="text-align:left;">Extra Person</td>
            @foreach (var item in Model.BillDetails)
            {
                <td>@item.ExtraPerson</td>
            }
        </tr>
        <tr>
            <td style="text-align:left;">GST</td>
            @foreach (var item in Model.BillDetails)
            {
                <td>@item.GST</td>
            }
        </tr>
        <tr>
            <td style="text-align:left;">Miscellaneous</td>
            @foreach (var item in Model.BillDetails)
            {
                <td>@item.Miscelleneous</td>
            }
        </tr>
        <tr>
            <td style="text-align:left;">Others 1</td>
            @foreach (var item in Model.BillDetails)
            {
                <td>@item.Other1</td>
            }
        </tr>
        <tr>
            <td style="text-align:left;">Others 2</td>
            @foreach (var item in Model.BillDetails)
            {
                <td>@item.Other2</td>
            }
        </tr>
        <tr>
            <td style="text-align:left;">Others 3</td>
            @foreach (var item in Model.BillDetails)
            {
                <td>@item.Other3</td>
            }
        </tr>
        <tr>
            <td style="text-align:left;">Others4</td>
            @foreach (var item in Model.BillDetails)
            {
                <td>@item.Other4</td>
            }
        </tr>
        <tr>
            <td style="text-align:left;">Total</td>
            @{ decimal tot = 0;
               decimal GTot=0; }
            @foreach (var item in Model.BillDetails)
            {
                tot = item.DayTotal;
                GTot += tot;
                <td style="font-weight:bolder;">@(tot)</td>
            }
        </tr>
    </table>
    <br />
    <table id="grid" width="100%">
        <tr>
            @{ 
                var ctw = new ChangeNumbersToWords();
            }
            <td style="text-align:left;" width="70%">Rupees @ctw.changeToWords(GTot.ToString())</td>
            <td width="10%">Advance</td>
            <td width="10%">@ViewBag.AdvanceAmt</td>
        </tr>
        <tr>
            <td width="70%"></td>
            <td width="10%">Bal. to pay</td>
            <td width="10%">@(GTot-(decimal)(ViewBag.AdvanceAmt ??0))</td>
        </tr>
    </table>

   
   
    </div>
    

<hr />
<h1>Receipts</h1>
<table class="table">    
    <tr>                
        <th>Receipt No.</th>
        <th>Type</th>
        <th>Date</th>
        <th>Name</th>
        <th>Amount</th>
        <th>Drawn On</th>        
    </tr>
    @foreach (var item in (IEnumerable<Receipt>) ViewBag.Receipts)
    {
        <tr>            
            <td>
                @Html.DisplayFor(modelItem => item.ReceiptID)
            </td>
            <td>
                @( (item.ReceiptTypeID == 1) ? "Full Amount" : (item.ReceiptTypeID == 2) ? "Advance" : "Balance")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DrawnOn)
            </td>
            
            </tr>
            }
    </table>

PetaStarter/Views/BillNonResd/DeleConfirm.cshtml
@model IEnumerable<DeMonte.BillDetail>

@if (Model.Count() > 0)
{
    <div class="MastDet">
        <center>
            <h2 class="section-to-print"><b>Changing your dates will cause the following to be deleted. Continue?</b></h2>
        </center>

        <table class="table">
            <tr>
                <th>Date</th>
                <th>Extra Person</th>
                <th>GST</th>
                <th>Miscelleneous</th>
                <th>Other 1</th>
                <th>Other 2</th>
                <th>Other 3</th>
                <th>Other 4</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExtraPerson)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GST)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Miscelleneous)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Other1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Other2)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Other3)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Other4)
                    </td>
                </tr>
            }

        </table>
    </div>
}

PetaStarter/Views/BillNonResd/Index.cshtml
@model PagedList.IPagedList<DeMonte.BillIndex>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Bills of Non Resident Customers";
}

    <center>
        <h2 class="section-to-print"><b>@ViewBag.Title</b></h2>    
    </center>
<p>
    
        @Html.ActionLink("Create New", "Manage")
    
</p>
<table class="table">
    <tr>       
       <th>Bill No.</th>
        <th>Customer</th>        
        <th>Date</th>        
        <th>Is Cancelled?</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>       
        <td>
            @Html.DisplayFor(modelItem => item.BillNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NonResdCust)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BDate)
        </td>        
        <td>
            @(item.Canceled ? "Cancelled" :  "" )
        </td>
        <td>
           @if(!item.Canceled)
           { 
                @Html.ActionLink("Edit", "Manage", new { id = item.BillID }, null)   @:|               
                @Html.ActionLink("Detail", "Details",  new { id = item.BillID }, null) @:|
                @Html.ActionLink("Receipts", "Index", "Receipt", new { BillID = item.BillID }, null) @:|
                @Html.ActionLink("Cancel", "Cancel", new { id = item.BillID }, null)
            }
        </td>
        
    </tr>
}

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))